html2pdf/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('html2pdf_app.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('html2pdf_app.urls')),
# ]

html2pdf_app/models.py
from django.db import models
import uuid
# import barcode
# from barcode.writer import ImageWriter
# from io import BytesIO 
# from django.core.files import File
# Create your models here.
import qrcode
import pdfkit
# import barcode
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw
from barcode.ean import EAN8


class Bill(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    # salary = models.CharField(max_length=1000,null=True,blank=True,default="")
    #stipend = models.CharField(max_length=1000,null=True,blank=True,default="")
    stipend = models.CharField(max_length=1000,default=0)
    joindate = models.DateField(auto_now_add=False,null=True)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)

    def __str__(self):
        return self.employee_name.capitalize()

    # def save(self, *args, **kwargs):
    #     EAN = barcode.get_barcode_class('ean8')
    #     #ean=EAN('5901234123457',writer=ImageWriter())
    #     ean = EAN(f'{self.employee_id}', writer=ImageWriter())
    #     buffer = BytesIO()
    #     ean.write(buffer)
    #     self.barcode.save(f'{self.employee_name}.png', File(buffer), save=False)
    #     super().save(*args, **kwargs)  
    
    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs) 




 
    # def save(self, *args, **kwargs):
    #     EAN = barcode.get_barcode_class('ean13')
    #     ean = EAN(f'{self.employee_id}', writer=ImageWriter)
    #     buffer = BytesIO()
    #     ean.write(buffer)
    #     self.barcode.save('barcode.png', File(buffer), save=False)
    #     return super().save(*args, **kwargs)

    class Meta:
        ordering = ('employee_id',)


class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password1 = models.CharField(max_length=100)
    password2 = models.CharField(max_length=100)
    
    def __str__(self):
        return self.email


class Rejected(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)

    def __str__(self):
        return self.employee_name.capitalize()

    class Meta:
        ordering = ('employee_id',)


class Reexp(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    joindate = models.DateField(auto_now_add=False,null=True)
    resignationdate = models.DateField(auto_now_add=False,null=True)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)


    def __str__(self):
        return self.employee_name.capitalize()

    # def save(self, *args, **kwargs):
    #     EAN = barcode.get_barcode_class('ean8')
    #     #ean=EAN('5901234123457',writer=ImageWriter())
    #     ean = EAN(f'{self.employee_id}', writer=ImageWriter())
    #     buffer = BytesIO()
    #     ean.write(buffer)
    #     self.barcode.save(f'{self.employee_name}.png', File(buffer), save=False)
    #     super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs) 

  



    class Meta:
        ordering = ('employee_id',)


class Appreciation(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    project_name = models.CharField(max_length=100)
    joindate = models.DateField(auto_now_add=False,null=True)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)

    def __str__(self):
        return self.employee_name.capitalize()

    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs) 

    
class Termination(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    discription = models.CharField(max_length=2000)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)

    def __str__(self):
        return self.employee_name.capitalize()

    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs)


class Offer(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    salary = models.CharField(max_length=1000)
    joindate = models.DateField(auto_now_add=False,null=True)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)

    def __str__(self):
        return self.employee_name.capitalize()

    
    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs) 


    class Meta:
        ordering = ('employee_id',)


class Intern(models.Model):
    employee_id = models.IntegerField()
    employee_email = models.EmailField()
    employee_name = models.CharField(max_length=100)
    job_type = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    joindate = models.DateField(auto_now_add=False,null=True)
    resignationdate = models.DateField(auto_now_add=False,null=True)
    date = models.DateField(auto_now_add=True,null=False)
    id = models.UUIDField(primary_key=True,unique=True, default=uuid.uuid4,editable = False)
    # barcode = models.ImageField(upload_to='image/', blank=True)
    qrcode= models.ImageField(upload_to='qrimage/', blank=True)


    def __str__(self):
        return self.employee_name.capitalize()

    # def save(self, *args, **kwargs):
    #     EAN = barcode.get_barcode_class('ean8')
    #     #ean=EAN('5901234123457',writer=ImageWriter())
    #     ean = EAN(f'{self.employee_id}', writer=ImageWriter())
    #     buffer = BytesIO()
    #     ean.write(buffer)
    #     self.barcode.save(f'{self.employee_name}.png', File(buffer), save=False)
    #     super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        qr_image = qrcode.make(self.id)
        qr_offset = Image.new('RGB', (310, 310), 'white')
        qr_offset.paste(qr_image)
        files_name = f'{self.id}.png'
        stream = BytesIO()
        qr_offset.save(stream, 'PNG')
        self.qrcode.save(files_name, File(stream), save=False)
        qr_offset.close()
        super().save(*args, **kwargs) 

  



    class Meta:
        ordering = ('employee_id',)

templates/appreciation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Appreciation details</title>
    <style type="text/css">
        @page {
            size: 7.5in 10.6in;
            margin: 0mm 16mm 24mm 16mm;
        }

        .bill-format .bill-header,
        .patient-details {
            display: inline-block;
        }

        .bill-format .bill-date,
        .sign {
            float: right;
        }

        .letter_conatiner {
            width: 100%;
        }

        .image_container {
            /* width: auto;
            margin: 0 auto; */
            display: flex;
            justify-content: space-around;
            align-items: center;
        }

        .top_image {
            height: 100px;
            width: 100%;

        }

        .container_body {
            width: 70%;
            margin: 0 auto;
        }

        .image_container2 {
            width: 100%;
            margin: 0 auto;
            margin-top: 35px;
        }

        .bottom_image {
            height: 350px;
            width: 100%;
        }

        .letter_body{
            margin-top: 45px;
        }
    </style>
</head>

<body>
    {% for pt in bill %}
    <div class="letter_conatiner">
        <div class="image_container">
            <img src="../static/image/upper.png" alt="" class="top_image">
            <img width="110px" style="float: left;" src="http://127.0.0.1:8000/media/qrimage/{{pt.id}}.png" alt="">
        </div>
        <h3 style="text-align:center; font-size: 20px;">Appreciation Certificate</h3>
        <div class="container_body mt-3">
            
            <h4 style="font-size: 15px;">Name of the Employee:- <span style="font-size: 15px; font-weight:bold;">{{ pt.employee_name.capitalize }}</span></h4>
            <h5>Employee ID:- {{ pt.employee_id }}</h5>
            <h5>Job Type:- {{ pt.job_type }}</h5>

            <!-- <img class="watermark" src="../static/image/chat-icon.png" /> -->

            <div class="letter_body mt-4">
                <h5>Dear <span>{{ pt.employee_name.capitalize }},</span></h5>
                <h5>Sub:- Appreciation Certificate For an employee</h5>
                <h5> We are writing this letter to appreciate you for the incredible work you have done on the launch of our
                    new {{pt.project_name}}. On behalf of the Management, I would like to recognize the extended working hours that
                    biggest launch of the company ever.

                    you have put in this project and amazing creativity that you have exhibited in making this launch the
                    The Management has been keeping a close watch on the progress of the project at every level as this is
                    one of the most prestigious products of the company and therefore, a lot was at stake with this project.

                    We have seen you work beyond working hours, work with dedication and focus, show amazing
                    professionalism dealing with all the challenges that came your way. Your commitment and zealous
                    approach towards your job is the reason behind the impressive performance that you have delivered.
                    Seeing such a remarkable performance, the Management has decided to announce an interim bonus for
                    you as a reward for your hard work and success. We are hopeful that other employees of our company.
                    will also take inspiration from your work and exhibit better performances.

                    With {{pt.project_name}} you have sent new benchmark for yourself and for others around you. We are expecting
                    that you will again impress us with your finest work in future and give us successful results.
                    On behalf of the Management, I thank you once again for such a brilliant performance.</h5>
                <h5>Thanking you,</h5>
            </div>
            <div class="letter_ending">
                <br>
                <h5>For <span>Shivila Technologies</span></h5>
                <h5>Manager HR</h5>
            </div>
        </div>

        <div class="image_container2">
            <img src="../static/image/bottom.png" alt="" class="bottom_image">
        </div>
        <p>{{pt.id}}</p> <p style="text-align:center;">page 1</p>
        {% comment %} <img width="110px" style="float: right;" src="http://127.0.0.1:8000/media/image/{{pt.employee_name}}.png" alt=""> {% endcomment %}
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/employeesearch.html
{% comment %} {% extends "base.html" %}


<center>
    <br></br>
    <h1 style= "justify-content: center;"> Employee Verfication Search Bar</h1>
    <form action="{% url 'employeeSearchView' %}" method="GET" value="{{request.GET.q}}" class="search_form">
        <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search"
            class="search_input" />
        <input type="submit" name="submit" value="Search" class="search_submit" />
    </form>
  </center>
  {% if submitbuttons == 'Search' and request.GET.q != '' %}
  {% if result %}
  <br>
  <h4>Results for {{ request.GET.q }}</h4>
  <br />
  
  {% for rlt in result %}
  
  <h5>Docs No :- {{rlt.id}}</h5>
  <br />
  
  <h5>Employee Name :- {{rlt.employee_name}}</h5>
  <br />
  
  <h5>Employee mail :- {{rlt.employee_email}}</h5>
  <br />
  
  <h5>Releaseing Date :- {{rlt.date}}</h5>
  <br />
  <h5>Designation :- {{rlt.designation}}</h5>
  <br />
  <h5>Job Type :- {{rlt.job_type}}</h5>
  <br />
  <h5>Join Date :- {{rlt.joindate}}</h5>
  <br />
  <h5>Resignation Date :- {{rlt.resignationdate}}</h5>
  <br />
  *******************************************
  <br>
  
  {% endfor %}
  {% else %}
  No search results for this query
  {% endif %}
  {% endif %} {% endcomment %}

templates/exp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Experience details</title>
    <style type="text/css">
        @page {
            size: 7.5in 10.6in;
            margin: 0mm 16mm 24mm 16mm;
        }

        .bill-format .bill-header,
        .patient-details {
            display: inline-block;
        }

        .bill-format .bill-date,
        .sign {
            float: right;
        }

        .letter_conatiner {
            width: 100%;
        }

        .image_container {
            /* width: auto;
            margin: 0 auto; */
            display: flex;
            justify-content: space-around;
            align-items: center;
        }

        .top_image {
            height: 100px;
            width: 100%;

        }

        .container_body {
            width: 70%;
            margin: 0 auto;
        }

        .image_container2 {
            width: 100%;
            margin: 0 auto;
            margin-top: 35px;
        }

        .bottom_image {
            height: 350px;
            width: 100%;
        }

        .letter_body{
            margin-top: 45px;
        }
    </style>
</head>

<body>
    {% for pt in bill %}
    <div class="letter_conatiner">
        <div class="image_container">
            <img src="../static/image/upper.png" alt="" class="top_image">
            <img width="110px" style="float: left;" src="http://127.0.0.1:8000/media/qrimage/{{pt.id}}.png" alt="">
        </div>
        <h3 style="text-align:center; font-size: 20px;">Employee Experience Certificate</h3>
        <div class="container_body mt-3">
            
            <h4 style="font-size: 12px;">Employee Name : <span style="font-size: 15px; font-weight:bold;">{{ pt.employee_name.capitalize }}</span></h4>
            <h5>Ref ID : {{ pt.date|date:"Y/md" }}/00{{ pt.employee_id }}</h5>
            <h5>Job Type : {{ pt.job_type }}</h5>
            <h5>Designation : {{ pt.designation }}</h5>
            <!-- <img class="watermark" src="../static/image/chat-icon.png" /> -->

            <div class="letter_body mt-4">
                <br>
                <h5>Dear <span>{{ pt.employee_name.capitalize }},</span></h5>
                <h5>Sub : Experience Certificate For an employee</h5>
                <h5> The experience he/she has gained in our organization. As the head of
                department in Shivila Technology. I hereby testify that this employee has
                worked in our company from date:- {{ pt.joindate }} for {{ pt.resignationdate }} and has
                gained experience in the<span style="font-size: 11px; font-weight:bold;">"{{ pt.designation }}"</span>.
                It was great pleasure working with {{ pt.employee_name.capitalize }} for his employment
                duration and proved himsel/herself as one of the most important assets
                of the organization. We wish him/her a good life and better opportunity
                of employment.</h5>
                <h5>Thanking you,</h5>
            </div>
            <div class="letter_ending">
                <br>
                <h5>For <span>Shivila Technologies</span></h5>
                <h5>Manager HR</h5>
            </div>
        </div>

        <div class="image_container2">
            <img src="../static/image/bottom.png" alt="" class="bottom_image">
        </div>
        <p>{{pt.id}}</p> 
        {% comment %} <img width="110px" style="float: right;" src="http://127.0.0.1:8000/media/image/{{pt.employee_name}}.png" alt=""> {% endcomment %}
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/internceremailattachment.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Email Attachment</title>
  <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="mt-5 mb-3">Email Attachment</h1>

          {% if error_message %}
          <div class="alert alert-primary" role="alert">
            {{error_message}}
          </div>
          {% endif %}

          {% if internemail_form %}
          <form method="POST" action ="" enctype="multipart/form-data">
            {% csrf_token %}
            {{internemail_form|crispy}}
          <button type="submit" class="btn btn-primary">Send Email</button>
          </form>
          {% endif %}

      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

templates/password_reset.html
{% extends 'base.html' %}


{% block content %}

	{% load crispy_forms_tags %}          

	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
  	</div> 

{% endblock %}

templates/termination_form.html
{% extends 'base.html' %}
{% block title %}Generate Termination Letter{% endblock %}
{% block nav_bill %}active{% endblock %}
{% block content %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    <strong>{{ field.label }}</strong><span>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

<style>
    body {
        height: 100vh;
        /* background: linear-gradient(rgba(57, 14, 211, 0.751), rgba(11, 128, 224, 0.591)); */
        background: linear-gradient(90deg, rgb(146, 225, 159) 0%, rgb(72, 245, 176)28%, rgba(66,222,196,1) 100%);
        box-sizing: border-box;
    }

    .form_container {
        background-color: white;
        border: none;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        /* background: linear-gradient(rgba(175, 74, 234, 0.623), rgba(232, 9, 135, 0.514)); */
        background-color: white;
        padding: 15px;
        border-radius: 10px;
    }
    .btn_container{
        width: 100%;
    }
    .submit_btn{
        width: 180px;
        margin: 0 460px;
        background-color: rgb(4, 197, 146);
        box-shadow: 0 2px 6px 0 rgba(0, 0, 0, 0.2), 0 3px 8px 0 rgba(0, 0, 0, 0.19);
        border: none;
    }
    .submit_btn:hover{
        background-color: rgb(21, 161, 124);
        color: black;
    }

    @media screen and (min-width:270px) and (max-width:500px) {
        .btn_container{
            display: flex;
            justify-content: center;
            align-items: center;
        }
     .submit_btn{
        margin: 0;
     }   
    }
</style>

<script>
    function myFun(){
        var correct_way = /^[A-Za-z]/;
        var a = document.getElementById("id_employee_name").value;

        if (a.length<3){
            document.getElementById("Message").innerHTML="** username must be 3 character";
            return false;
        }
        if (a.length>20){
            document.getElementById("Message").innerHTML="** username must be less than 20 character";
            return false;
        }
        if (a.match(correct_way))
            true;
            else{
                document.getElementById("Message").innerHTML="** only Alphabets are allowed";
                return false;

        }
    }
</script>
<form method="post" class="form_container" onsubmit=" return myFun()">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group">
                <label for="id_employee_id" class="form-control-label mt-3 mb-3">Employee id</label>
                <input type="number" name="employee_id" class="form-control bg-light" maxlength="150" required
                    id="id_employee_id">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group">
                <label for="id_employee_email" class="form-control-label mt-3 mb-3">Employee Email</label>
                <input type="text" name="employee_email" class="form-control bg-light" maxlength="150" required
                    id="id_employee_email">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group">
                <label for="id_employee_name" class="form-control-label mt-3 mb-3">Employee name:</label>
                <input type="text" name="employee_name" class="form-control bg-light" maxlength="100" required
                    id="id_employee_name">
                <p id= "Message" ></p>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            {% comment %} <div class="form-group">
                <label for="id_job_type" class="form-control-label mt-3 mb-3">Job Type</label>
                <input type="dropdown-item" name="job_type" class="form-control bg-light" required id="id_job_type"
                    maxlength="50">
            </div> {% endcomment %}
            <div class = "form-group">
                <label for="id_job_type" class="form-control-label mt-3 mb-3">Job Type</label>

                <select id="id_job_type" name="job_type"  class="form-control input1" required >

                    <option >------------------Select-----------------</option>
                    <option >Internship(Full Time)</option>
                    <option >Part Time</option>

                    <option >Remote(WFH)</option>

                    <option >Internship</option>

                    <option >WFO</option>

                </select>
            </div>    
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            {% comment %} <div class="form-group">
                <label for="id_designation" class="form-control-label mt-3 mb-3">Designation:</label>
                <input type="text" name="designation" class="form-control bg-light" required id="id_designation"
                    maxlength="60">
            </div> {% endcomment %}
            <div class = "form-group">
                <label for="id_designation" class="form-control-label mt-3 mb-3">Designation</label>

                <select id="id_designation" name="designation"  class="form-control input1 " required >

                    <option >------------------Select-----------------</option>
                    <option >Python Developer</option>
                    <option >django Developer</option>
                    <option >Java Developer</option>
                    <option >PHP Developer</option>
                    <option >JavaScript Developer</option>
                    <option >Node.js Developer</option>
                    <option >C#,.ASP, .net Developer</option>
                    <option >React Developer</option>
                    <option >Frontend Developer</option>
                    <option >Full stack Developer</option>
                    <option >Manual Testing</option>
                    <option >Cloud Computing</option>
                    <option >IT Support</option>
                    <option >Content Writer</option> 
                    <option >DevOps</option>
                    <option >Automation</option> 
                    <option >Testing</option>
                    <option >Angular Developer</option>
                    <option >Android Developer</option>
                    <option >Flutter Developer</option>
                    <option >Flutter Internship</option>
                    <option >UI/UX Developer</option>
                    <option >SEO Executive</option>
                    <option >Tele Marketing</option>
                    <option >Tele Caller</option>
                    <option >Team Lead</option>
                    <option>Sales Executive</option>
                    <option >Digital Marketing</option>
                    <option >Frontend(Html, css, js)</option>
                    <option >Frontend(Html5, css3, js)</option>

                </select>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group">
                <label for="id_discription" class="form-control-label mt-3 mb-3">Reason of Termination</label>
                <input type="text" name="discription" class="form-control bg-light" required id="id_discription">
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="form-group">
                <label for="id_date" class="form-control-label mt-3 mb-3">Releasing Date:</label>
                <input type="date" class="form-control bg-light" name="date" required id="id_date">
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-12 btn_container">
            <button type="submit" class="btn btn-success mt-4 submit_btn">Submit details</button>
        </div>
    </div>
</form>
{% endblock %}